### ISSUE TITLE
[Business Approvals Kit - BUG] Received approval request - not working

### ISSUE THREAD

**Issue by ahmadpirani** [microsoft/powercat-business-approvals-kit#173]
### Describe the issue

This effectively makes the entire approval kit unusable.

Error Details: TypeError: Cannot use 'in' operator to search for '@odata.type' in null
    at e.getLookupValue (wrapped.https://content.powerapps.com/resource/app/8trp4ooifhdnc/publish/js/pa.core.bundle1.js;:25:360042)
    at e.getValue (wrapped.https://content.powerapps.com/resource/app/8trp4ooifhdnc/publish/js/pa.core.bundle1.js;:25:361092)
    at Object.eval [as getValue] (wrapped.https://content.powerapps.com/resource/app/led4525gomou1/ctrllib/PCFControls/js/PCFControlWrapper.js;:16:1431497)
    at g (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:5527)
    at eval (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:4207)
    at eval (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:4621)
    at eval (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:4687)
    at Array.map (<anonymous>)
    at eval (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:1502)
    at Array.map (<anonymous>)
    at eval (wrapped.https://pafeblobprodby.blob.core.windows.net/20231229t000000zc885306112364e0ca139f1f7609a333a/68f2470c-9f0c-4c57-a4ec-5156f621b4df/web/cat_homepagereimagined_709bf/web/PCFControls/cat_PowerCAT.FluentDetailsList/PowerCAT.FluentDetailsList.bundle.js;:16:1392)
    at we (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:284:293)
    at He (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:297:464)
    at ph (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:297:294)
    at oh (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:296:399)
    at zj (https://content.powerapps.com/resource/app/hg86122f107g8/publish/js/pa.oss.bundle2.js:433:237)

Activity Id: 6bfc1a9f-4587-44c1-a730-fb43694c52d3

![image](https://github.com/microsoft/powercat-business-approvals-kit/assets/11561396/85ebde83-e50d-4ab6-9284-330cd5b83bff)

### What solution version are you using?

Whichever is the latest

### What app or flow are you having the issue with?

none

### Steps To Reproduce

Go to Home page to view your received approval request(s).

AB#1914

**Comment by shrikant-singh31** [comment]
Closing as the issue was fixed with the Feb-24 release for issue https://github.com/microsoft/powercat-business-approvals-kit/issues/152
