### ISSUE TITLE
[Business Approvals Kit - BUG] Dynamic Approval Failure

### ISSUE THREAD

**Issue by MCSDWes** [microsoft/powercat-business-approvals-kit#191]
### Describe the issue

Anytime I use Dynamic Approvals the flow fails.  I'm using the Manager of Initiator as the dynamic approval.  The Action Step is - When Data Instance Approver is added.  Not sure if this is a bug or something wrong with the data on my end.
![Power-Apps-Solutions-Business-Approval-Kit](https://github.com/microsoft/powercat-business-approvals-kit/assets/68615610/d22a0251-82d2-47ea-bf3c-5344504ca3b4)

### Expected Behavior

Flow to successfully pull the Manager of the requester.  I'm using the Contoso Coffee Machine App and flow.  The flow works fine if I hardcode the users name in but as soon as I change to Dynamic Approver the flow fails.

### What solution version are you using?

Latest January 2024

### What app or flow are you having the issue with?

BA Core | Child | Get Dynamic Data Instance

### Steps To Reproduce

Go to Processes
Select the Machine Requets (Process Designer)
Modify the Submit Node
Change to "Manager of Initiator"
Select Add
Click Save on the Process
Once the process is saved successfully
Click Publish
Click Publish at the bottom of the page
Submit a request and the approval request is never sent and errors out on the BA Core | Child | Get Dynamic Data Instance

### Anything else?

**Full Error Message - When Data Instance Approver is added**
The request failed. Error code: '0x80040203'. Error Message: 'Exception parsing _cat_workflowinstance_value eq 'faa9378d-11b7-ee11-a569-000d3a4e8b12' and _cat_runtimedata_value eq '' submitted for attribute filterexpression of callback registration. Target entity: cat_businessapprovaldatainstance. Exception: Microsoft.OData.ODataException: A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'.
   at Microsoft.OData.UriParser.BinaryOperatorBinder.PromoteOperandTypes(BinaryOperatorKind binaryOperatorKind, SingleValueNode& left, SingleValueNode& right, TypeFacetsPromotionRules facetsPromotionRules)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)
   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
   at System.Web.OData.Query.FilterQueryOption.get_FilterClause()
   at Microsoft.Crm.ObjectModel.EdmModelEvaluator.EvaluateFilterExpression(String filterExpression, ODataQueryOptions queryOptions)
   at Microsoft.Crm.ObjectModel.EdmModelEvaluator.EvaluateFilterExpression(String filterExpression)
   at Microsoft.Crm.ObjectModel.CallbackRegistrationService.<>c.<.cctor>b__79_0(EdmModelEvaluator evaluator, String testValue)
   at Microsoft.Crm.ObjectModel.CallbackRegistrationService.ValidateInputEntity(IBusinessEntity entity, ExecutionContext context, IFeatureDetailContainer featureDetailContainer)'.

AB#2096

**Comment by marcelhuszar** [comment]
happened to me as well

**Comment by MCSDWes** [comment]
@marcelhuszar - Good to know its a true bug and not something with the data on my end.

**Comment by MCSDWes** [comment]
Verified its still an issue with the February Release - 1.0.20240206.2

**Comment by MCSDWes** [comment]
As a workaround, I added two variables in my scenario called Manager and Director.  In the flow when the record was submitted I added a Get Manager action to grab the first approver, then added a second Get Manager for the Director's approval.  I fed that data into the variables using the UPN from each action and everything seemed to work.  It should be pulling those automatically.

**Comment by MCSDWes** [comment]
@shrikant-singh31 - I can confirm this is now working in the March release.  There is also an issue with the "Manager of Last Approver" which I will submit a separate bug request on that one.  I appreciate all your help as the Approvals Kits is a huge time saver and can't wait until it gets fully released.
